import asyncio
import argparse
from playwright.async_api import async_playwright

NETSCAPE_TEMPLATE = """# Netscape HTTP Cookie File
# This file was generated by export_cookies.py
# Format: domain\tflag\tpath\tsecure\texpiration\tname\tvalue
"""


async def save_cookies(context, output_file):
    cookies = await context.cookies()
    lines = [NETSCAPE_TEMPLATE]

    for cookie in cookies:
        domain = cookie.get("domain", "")
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = cookie.get("path", "/")
        secure = "TRUE" if cookie.get("secure") else "FALSE"
        expiration = str(int(cookie["expires"])) if cookie.get("expires") else "0"
        name = cookie.get("name", "")
        value = cookie.get("value", "")

        line = f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n"
        lines.append(line)

    with open(output_file, "w", encoding="utf-8") as f:
        f.writelines(lines)

    print(f"\n✅ Cookies exported successfully to: {output_file}\n")


async def run_exporter(output_path):
    async with async_playwright() as p:
        print("\n📌 Launching Chromium browser...")
        print("➡ Please log in to your YouTube/Google account normally.")
        print("➡ When you're done, return here and press ENTER.\n")

        browser = await p.chromium.launch(headless=False)
        context = await browser.new_context()
        page = await context.new_page()

        await page.goto("https://www.youtube.com", wait_until="load")

        input("🔐 Log in fully, then press ENTER here to export cookies...")

        await save_cookies(context, output_path)

        await browser.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export YouTube cookies to cookies.txt")
    parser.add_argument("--out", type=str, default="cookies.txt", help="Output cookie file")
    args = parser.parse_args()

    asyncio.run(run_exporter(args.out))

